### ISSUE TITLE
シグナルのバグ

### ISSUE THREAD

**Issue by teamaru** [teamaru/42_minishell#85]
・存在しないコマンドを入力した際のエラーメッセージがずれていました。
・catをctrl-Cで終了させた際の終了ステータスがずれていました (minishell: 65, bash: 130)。
・catをctrl-で終了させた際の終了ステータスがずれていました (minishell: 65, bash: 131)
・sleep中にctrl-Cで終了させた場合に不要なメッセージが表示されてしまっていました。
・パイプでコマンドをつないだ際の終了ステータスがパイプの最後のコマンドの終了ステータスを適切に反映できていませんでした (例: echo hello | sleep 3をctrl-Cで終了させた場合)。

**Comment by public-jun** [comment]
- [ ] 存在しないコマンドを入力した際のエラーメッセージがずれる
- [ ] catをctrl-Cで終了させた際の終了ステータスのずれ (minishell: 65, bash: 130)。
- [ ] catをctrl-で終了させた際の終了ステータスのずれ (minishell: 65, bash: 131)
- [ ] パイプでコマンドをつないだ際の終了ステータスがパイプの最後のコマンドの終了ステータスを適切に反映できていない(例: echo hello | sleep 3をctrl-Cで終了させた場合)。
