### ISSUE TITLE
リダイレクション

### ISSUE THREAD

**Issue by teamaru** [teamaru/42_minishell#88]
echo test > $HOGEの際に、No such file or directoryのエラーメッセージが出てしまっていました。redirectionnが失敗した際に、そのまま抜けるように修正が必要かと思います

**Comment by public-jun** [comment]
- [ ] リダイレクション失敗時にexitする

**Comment by public-jun** [comment]
err_msg`ambiguous redirect` について

expand部分で出力しているが、その場合、パイプラインで複数プロセスを実行した際に一つしかエラーメッセージが出力されない。

**bash**
```bash
echo a > $HGOE | echo a > $HOGE
bash: $HOGE: ambiguous redirect
bash: $HOGE: ambiguous redirect
```

**minishell**
```bash
echo a > $HGOE | echo a > $HOGE
minishell: ambiguous redirect
```

expand中の`split_token()`中
```c
if (is_file_path(*token) && token_listsize(new_tokens) != 1)
    return (print_err_msg(ERR_MSG_AMBGS_RDRCT, GNRL_ERR));
```
部分では出力をせずに`execute`部分でエラーを出力するようにする

**Comment by public-jun** [comment]
case` > file | cat < no_such_file\nexit`
について

```bash
> file | cat < no_such_file
 bash: line 1: no_such_file: No such file or directory
```

```bash
> file | cat < no_such_file
bash: line 1: no_such_file: No such file or directory
```

エラーメッセージが異なる

リダイレクト部分のエラーが全て同じメッセージになるのが原因
